# Generated by Django 4.1.5 on 2023-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('resumen', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('tipocultivo', models.JSONField()),
                ('talentoHumano', models.JSONField()),
                ('actividadesClave', models.JSONField()),
                ('conclusiones', models.TextField()),
            ],
        ),
    ]
