# Generated by Django 4.1.5 on 2023-02-09 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agrosCRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='id',
        ),
        migrations.AlterField(
            model_name='informe',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
